Repository SF-Algorithm-08/Study-Algorithm, pull requests merged in 2021-05, with the labels that each got.

#90 김민기 : 4월 5주차 풀이
  김민기/4월 5주차/boj0127_210430_2616_g4/README.md
  김민기/4월 5주차/boj0127_210430_2616_g4/백준_2616번_소형기관차.java
  김민기/4월 5주차/boj0128_210501_1344_g4/README.md
  김민기/4월 5주차/boj0128_210501_1344_g4/백준_1344번_축구.java
  김민기/4월 5주차/boj0130_210503_17825_g2/README.MD
  김민기/4월 5주차/boj0130_210503_17825_g2/백준_17825번_주사위윷놀이.java
  김민기/5월 1주차/boj0131_210504_1256_g4/README.md
  김민기/5월 1주차/boj0131_210504_1256_g4/백준_1256번_사전.java
  김민기/5월 1주차/boj0132_210505_12763_g2/README.md
  김민기/5월 1주차/boj0132_210505_12763_g2/백준_12763번_지각하면안돼.java
  김민기/5월 1주차/boj0133_210505_10993_g4/README.md
  김민기/5월 1주차/boj0133_210505_10993_g4/백준_10993번_별찍기18.java
Labels: DP, 구현, 순열/조합

#85 배수연 : 4월 5주차 풀이
  배수연/4월 5주차/4월 5주차 풀이.md
  배수연/4월 5주차/BOJ_G2_17825.java
  배수연/4월 5주차/BOJ_G4_1344.java
  배수연/4월 5주차/BOJ_G4_2616.java
Labels: DP, 구현, 순열/조합

#94 배수연 : 5월 1주차 풀이
  배수연/5월 1주차/5월 1주차 풀이.md
  배수연/5월 1주차/BOJ_G3_1256.java
  배수연/5월 1주차/BOJ_G4_10993.java
Labels: DP, 다익스트라, 재귀

#97 김민기 : 5월 1주차 연습 & 5월 2주차 풀이
  김민기/5월 1주차 연습/boj0135_210509_17298_g4/README.md
  김민기/5월 1주차 연습/boj0135_210509_17298_g4/백준_17298번_오큰수.java
  김민기/5월 1주차 연습/boj0139_210510_1774_g4/README.md
  김민기/5월 1주차 연습/boj0139_210510_1774_g4/백준_1774번_우주신과의교감.java
  김민기/5월 1주차 연습/boj0139_210510_1774_g4/백준_1774번_우주신과의교감_kruskal.java
  김민기/5월 2주차/boj0136_210509_1756_g5/README.md
  김민기/5월 2주차/boj0136_210509_1756_g5/백준_1756번_피자굽기.java
  김민기/5월 2주차/boj0137_210509_1089_g5/README.md
  김민기/5월 2주차/boj0137_210509_1089_g5/백준_1089_스타트링크타워2.java
  김민기/5월 2주차/boj0138_210510_1593_g4/README.md
  김민기/5월 2주차/boj0138_210510_1593_g4/백준_1593번_문자해독.java
Labels: MST, 구현, 스택, 슬라이딩 윈도우, 이분 탐색

#98 최은송: 5월 1주차 연습 & 5월 2주차 풀이
  최은송/5월 1주차 연습/BOJ_G4_17298_오큰수/BOJ_G4_17298_오큰수.java
  최은송/5월 1주차 연습/BOJ_G4_17298_오큰수/Readme.md
  최은송/5월 1주차 연습/BOJ_G4_1774_우주신과의교감/BOJ_G4_1774_우주신과의교감.java
  최은송/5월 1주차 연습/BOJ_G4_1774_우주신과의교감/Readme.md
  최은송/5월 2주차/5월 2주차 풀이 최은송.md
  최은송/5월 2주차/BOJ_G4_1593_문자해독.java
  최은송/5월 2주차/BOJ_G5_1089_스타트링크.java
  최은송/5월 2주차/BOJ_G5_1756_피자굽기.java
Labels: MST, 구현, 문자열, 슬라이딩 윈도우

#96 배수연 : 5월 1주차 연습 & 5월 2주차 풀이
  배수연/5월 1주차 연습/5월 1주차 연습 풀이.md
  배수연/5월 1주차 연습/BOJ_G4_17298.java
  배수연/5월 1주차 연습/BOJ_G4_1774.java
  배수연/5월 2주차/5월 2주차 풀이.md
  배수연/5월 2주차/BOJ_G4_1593.java
  배수연/5월 2주차/BOJ_G5_1089.java
  배수연/5월 2주차/BOJ_G5_1756.java
Labels: MST, 구현, 문자열, 슬라이딩 윈도우

#99 박규동: 5월 1주차 연습 & 5월 2주차 풀이
  박규동/5월 1주차 연습&&5월 2주차/# 5월 1주차 연습 && 5월 2주차 문제 정리.md
  박규동/5월 1주차 연습&&5월 2주차/Main_1089.java
  박규동/5월 1주차 연습&&5월 2주차/Main_1593.java
  박규동/5월 1주차 연습&&5월 2주차/Main_17298.java
  박규동/5월 1주차 연습&&5월 2주차/Main_1756.java
  박규동/5월 1주차 연습&&5월 2주차/Main_1774.java
Labels: MST, 구현, 스택, 슬라이딩 윈도우, 이분 탐색

#107 김민기 : 5월 3주차 풀이
  김민기/5월 3주차/boj0143_210517_16472_g2/README.md
  김민기/5월 3주차/boj0143_210517_16472_g2/백준_16472번_고냥이.java
  김민기/5월 3주차/boj0144_210517_8913_g3/README.md
  김민기/5월 3주차/boj0144_210517_8913_g3/백준_8913_문자열뽑기.java
  김민기/5월 3주차/boj0145_210520_16234_g5/README.md
  김민기/5월 3주차/boj0145_210520_16234_g5/백준_16234번_인구이동.java
Labels: BFS, 구현, 문자열, 완전 탐색, 재귀, 투포인터

#109 김나은 : 5월 3주차 풀이
  김나은/5월 3주차/5월 3주차 문제 정리.md
  김나은/5월 3주차/BOJ_G2_16472_고냥이.java
  김나은/5월 3주차/BOJ_G3_8913_문자열뽑기.java
  김나은/5월 3주차/BOJ_G5_16234_인구이동.java
Labels: BFS, 구현, 문자열, 재귀, 투포인터

#104 배수연 : 5월 3주차 풀이
  배수연/5월 3주차/5월 3주차 풀이.md
  배수연/5월 3주차/BOJ_G2_16472.java
  배수연/5월 3주차/BOJ_G3_8913.java
  배수연/5월 3주차/BOJ_G5_16234.java
Labels: BFS, 구현, 문자열, 재귀, 투포인터

#105 최은송 : 5월 3주차 풀이
  최은송/5월 3주차/BOJ_G2_16472_고냥이.java
  최은송/5월 3주차/BOJ_G3_8913_문자열뽑기.java
  최은송/5월 3주차/BOJ_G5_16234_인구이동.java
  최은송/5월 3주차/Readme.md
Labels: BFS, 구현, 문자열, 재귀, 투포인터

#108 박규동 : 5월 3주차 풀이
  박규동/5월 3주차/5월 3주차 문제 정리.md
  박규동/5월 3주차/Main_16234.java
  박규동/5월 3주차/Main_16472.java
Labels: BFS, 구현, 문자열, 투포인터
