Repository SF-Algorithm-08/Study-Algorithm, pull requests merged in 2021-04, with the labels that each got.

#65 김민기 : 4월 2주차 풀이
  김민기/4월 2주차/boj0094_210408_4811_g5/README.md
  김민기/4월 2주차/boj0094_210408_4811_g5/백준_4811번_알약.java
  김민기/4월 2주차/boj0095_210408_5525_s2/README.md
  김민기/4월 2주차/boj0095_210408_5525_s2/백준_5525번_IOIOI.java
  김민기/4월 2주차/boj0096_210408_2589_g5/README.md
  김민기/4월 2주차/boj0096_210408_2589_g5/백준_2589번_보물섬.java
Labels: BFS, DP, 문자열

#73 김민기 : 4월 3주차 풀이
  김민기/4월 3주차/boj0100_210411_2644_s2/README.md
  김민기/4월 3주차/boj0100_210411_2644_s2/백준_2644번_촌수계산.java
  김민기/4월 3주차/boj0101_210411_15685_g4/README.md
  김민기/4월 3주차/boj0101_210411_15685_g4/백준_15685번_드래곤커브.java
  김민기/4월 3주차/boj0102_210411_2502_s1/README.md
  김민기/4월 3주차/boj0102_210411_2502_s1/백준_2502_떡먹는호랑이.java
Labels: DP, Disjoint-Set, 구현

#80 김민기 : 4월 4주차 풀이
  김민기/4월 4주차/boj0116_210417_4386_g4/README.md
  김민기/4월 4주차/boj0116_210417_4386_g4/백준_4386번_별자리만들기.java
  김민기/4월 4주차/boj0117_210419_1043_g4/README.md
  김민기/4월 4주차/boj0117_210419_1043_g4/백준_1043번_거짓말.java
  김민기/4월 4주차/boj0118_210419_1938_g2/README.md
  김민기/4월 4주차/boj0118_210419_1938_g2/백준_1938번_통나무옮기기.java
Labels: BFS, Disjoint-Set, MST

#79 최은송 : 4월 4주차 풀이
  최은송/4월 4주차 연습/BOJ_G4_19268_스타트택시/BOJ_G4_19268_스타트택시.java
  최은송/4월 4주차 연습/BOJ_G4_19268_스타트택시/Readme.md
  최은송/4월 4주차 연습/BOJ_S1_1669_멍멍이쓰다듬기/BOJ_S1_1669_멍멍이쓰다듬기.java
  최은송/4월 4주차 연습/BOJ_S1_1669_멍멍이쓰다듬기/Readme.md
  최은송/4월 4주차/4월 4주차 풀이.md
  최은송/4월 4주차/BOJ_G2_1938_통나무옮기기/BOJ_G2_1938_통나무옮기기.java
  최은송/4월 4주차/BOJ_G2_1938_통나무옮기기/Readme.md
  최은송/4월 4주차/BOJ_G4_1043_거짓말/BOJ_G4_1043_거짓말.java
  최은송/4월 4주차/BOJ_G4_1043_거짓말/Readme.md
  최은송/4월 4주차/BOJ_G4_4386_별자리만들기/BOJ_G4_4386_별자리만들기.java
  최은송/4월 4주차/BOJ_G4_4386_별자리만들기/Readme.md
Labels: DFS, MST, 구현

#78 배수연 : 4월 4주차 풀이
  배수연/4월 4주차/4월 4주차 풀이.md
  배수연/4월 4주차/BOJ_G2_1938.java
  배수연/4월 4주차/BOJ_G4_1043.java
  배수연/4월 4주차/BOJ_G4_4386.java
Labels: BFS, Disjoint-Set, MST, 구현
